/****************************************************************************/
/*                           COPYRIGHT NOTICE                               */
/****************************************************************************/
/* A PL/I Compiler for the Win32 platform.                                  */
/* Copyright (C) 1997 - 2006 Hugh Gleaves.                                    */
/*                                                                          */
/* This program is free software; you can redistribute it and/or            */
/* modify it under the terms of the GNU General Public License              */
/* as published by the Free Software Foundation; either version 2           */
/*                                                                          */
/* This program is distributed in the hope that it will be useful,          */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of           */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            */
/* GNU General Public License for more details.                             */
/*                                                                          */
/* You should have received a copy of the GNU General Public License        */
/* along with this program; if not, write to the Free Software              */
/* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 */
/* USA.                                                                     */
/****************************************************************************/

# define CV_SHORT_TO_DEC     "spt_cv_short_to_dec"
# define CV_DEC_TO_SHORT     "spt_cv_dec_to_short"

# define CV_DEC_TO_DEC       "pli$dec_to_dec"
# define CV_CAR_TO_ATC       "pli$car_to_atc"
# define CV_DEC_TO_BIN       "pli$dec_to_bin"
# define CV_DEC_TO_CHR       "pli$dec_to_chr"
# define CV_PIC_TO_DEC       "pli$pic_to_dec"
# define CV_DEC_TO_PIC       "pli$dec_to_pic"
# define CV_FLT_TO_DEC       "pli$flt_to_dec"
# define CV_DEC_TO_FLT       "pli$dec_to_flt"

/**************************** end of include ********************************/
