/****************************************************************************/
/*                           COPYRIGHT NOTICE                               */
/****************************************************************************/
/* A PL/I Compiler for the Win32 platform.                                  */
/* Copyright (C) 1997 - 2006 Hugh Gleaves.                                    */
/*                                                                          */
/* This program is free software; you can redistribute it and/or            */
/* modify it under the terms of the GNU General Public License              */
/* as published by the Free Software Foundation; either version 2           */
/*                                                                          */
/* This program is distributed in the hope that it will be useful,          */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of           */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            */
/* GNU General Public License for more details.                             */
/*                                                                          */
/* You should have received a copy of the GNU General Public License        */
/* along with this program; if not, write to the Free Software              */
/* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 */
/* USA.                                                                     */
/****************************************************************************/

/****************************************************************************/
/* This file simply defines some straightforward replace names for raw HEX  */
/* opcodes. Be sure to leave a one-line gap when there is a discontinuity   */
/* in succesive values, this makes it easy to insert new opcodes in the     */
/* right place in future.                                                   */
/****************************************************************************/

# define OP00     '\x00'
# define OP01     '\x01'
# define OP02     '\x02'	  
# define OP03     '\x03'

# define OP06     '\x06'
# define OP07     '\x07'

# define OP0E     '\x0E'

# define OP10     (chur)0x10
# define OP11     '\x11'
# define OP12     '\x12'
# define OP13     '\x13'

# define OP16     '\x16'
# define OP17     '\x17'

# define OP18     '\x18'
# define OP19     '\x19'
# define OP1A     '\x1A'
# define OP1B     '\x1B'

# define OP1E     '\x1E'
# define OP1F     '\x1F'

# define OP28     '\x28'
# define OP29     '\x29'
# define OP2A     '\x2A'
# define OP2B     '\x2B'

# define OP38     '\x38'
# define OP39     '\x39'
# define OP3A     '\x3A'
# define OP3B     '\x3B'

# define OP68     '\x68'

# define OP74     '\x74'
# define OP75     '\x75'
# define OP76     '\x76'
# define OP77     '\x77'
# define OP78     '\x78'
# define OP79     '\x79'
# define OP7A     '\x7A'
# define OP7B     '\x7B'
# define OP7C     '\x7C'
# define OP7D     '\x7D'
# define OP7E     '\x7E'
# define OP7F     '\x7F'
# define OP80     '\x80'
# define OP81     '\x81'

# define OP83     '\x83'

# define OP88     '\x88'
# define OP89     '\x89'
# define OP8A     '\x8A'
# define OP8B     '\x8B'
# define OP8C     '\x8C'
# define OP8D     '\x8D'
# define OP8E     '\x8E' 
# define OP8F     '\x8F'

# define OPB0     '\xB0'

# define OPB8     '\xB8'

# define OPC2     '\xC2'

# define OPC6     '\xC6'
# define OPC7     '\xC7'
# define OPC8     '\xC8'
# define OPC9     '\xC9' 
# define OPCA     '\xCA'
# define OPCB     '\xCB'

# define OPCD     '\xCD'

# define OPDE     '\xDE'
# define OPDF     '\xDF'

# define OPE9     '\xE9'

# define OPEB     '\xEB'

# define OPF6     '\xF6'
# define OPF7     '\xF7'

# define OPFE     '\xFE'
# define OPFF     '\xFF'

/******************************* end of include *****************************/

