
/****************************************************************************/
/*     This file defines constants for use in the graphics system calls.    */
/****************************************************************************/

   % replace TXT_40x25_16_NB               by 0;   /* No color burst */
   % replace TXT_40x25_16                  by 1; 
   % replace TXT_80x25_16_NB               by 2;   /* No color burst */
   % replace TXT_80x25_16                  by 3;    

   % replace GFX_320x200_4                 by 4;
   % replace GFX_320x200_4_B               by 5;
   % replace GFX_640x200_2                 by 6;     
   % replace GFX_160x200_16                by 8;  
   % replace GFX_320x200_16_a              by 9;  
   % replace GFX_640x200_4                 by 10;  
   % replace GFX_320x200_16_b              by 13;
   % replace GFX_640x200_16                by 14;   
   % replace GFX_640x350_2                 by 15;  
   % replace GFX_640x350_4                 by 16;  /* 64k Card   */  
   % replace GFX_640x350_16                by 16;  /* 128k Card  */
   % replace GFX_640x480_2                 by 17;  
   % replace GFX_640x480_16                by 18;  /* VGA only   */
   % replace GFX_320x200_256               by 19;   

/**************************** end of include *******************************/
