

/****************************************************************************/
/*       This file defines constants for use with the MS mouse driver.      */
/****************************************************************************/

   % replace INT_DISABLED                  by 0;   
   % replace INT_30_SEC                    by 2;    /* bit  1 */
   % replace INT_50_SEC                    by 4;    /* bit  2 */
   % replace INT_100_SEC                   by 8;    /* bit  3 */
   % replace INT_200_SEC                   by 16;   /* bit  4 */

/**************************** end of include *******************************/

